### ISSUE TITLE
what does runtime for a node mean

### ISSUE THREAD

**Issue by zmsunnyday** [IFL-CAMP/supra#103]
Hi Supra team, there is a runtime show in the node box on GUI. What does this mean? Does it is the proccessing time used by the node?
![image](https://user-images.githubusercontent.com/16131776/100195608-92a3a300-2f32-11eb-9119-48b1b79c2bff.png)

**Comment by goeblr** [comment]
Hey,
That is a very good question!
For most nodes you can see there it shows the time it took on the CPU to perform their actions - that means to enqueue the required CUDA kernel launches since most are fully asynchronous. Some nodes might wait for the GPU to finish the computations though, in which case that time will also reflect the GPU time spent.

If you want to know exactly what is going on, you can use the "StreamSyncNode" which will wait for all GPU computation of an incoming image to be finished. 
![grafik](https://user-images.githubusercontent.com/7439248/101948731-d6fd9700-3bf2-11eb-98a4-d31d5f0d992b.png)
In this example 

- The Beamforming node spends 0.27 ms (average) on the CPU
- ... while the actual computation takes 3.7 ms in total.
- The HilbertFirEnvelopeNode takes below 1 ms in total, including the GPU kernels.

I hope that helps!

**Comment by zmsunnyday** [comment]
Thanks, @goeblr , it is very helpful.
